version: '3'

services:
  application:
    image: mufasa1976/calcmaster-spring-boot-3

  nginx:
    image: nginx:stable
    depends_on:
      - application
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
