version: '3'

services:
  application:
    image: mufasa1976/calcmaster
    ports:
      - 127.0.0.1:5005:5005
    environment:
      SPRING_PROFILES_ACTIVE: docker
    volumes:
      - ./config:/opt/config

  nginx:
    image: nginx:stable
    depends_on:
      - application
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
